# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZiLiao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZiLiao
pod 'AFNetworking', '2.6.1'
end
